name: JEUX CI
on: 
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  my_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm" 

      - name: Install
        run: npm ci

      - name: Run Linter
        # on utilise une action qui transforme les erreurs Eslint en annotation Github
        run: npm run lint -- --format=stylish

      - name: Security Audit
        run: npm audit --audit-level=high #s'arrête si une faille grave est trouvé

      - name: Run Tests
        # --ci et le reporter github-action crées les annotations automatiques
        run: npm test -- --ci --reporters=default --reporters=github-actions
        
      - name: Build Project
        run: npm run build

      - name: Upload Documentation
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: documentation-site
          path: docs/

      - name: Upload Build Output
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: project-build
          path: dist/